apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "statping.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "statping.labels" . | nindent 4 }}
    app.kubernetes.io/component: statping
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if or .Values.ingress.tls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "statping.fullname" . }}
                port:
                  name: http
    {{- end }}
