{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "statping.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "statping.labels" . | nindent 4 }}
    app.kubernetes.io/component: statping
{{- end -}}
