apiVersion: v1
kind: Service
metadata:
  name: {{ include "statping.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "statping.labels" . | nindent 4 }}
    app.kubernetes.io/component: statping
  annotations:
  {{- if .Values.service.annotations }}
  {{- include "common.tplvalues.render" (dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "statping.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
