{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "statping.serviceAccountName" . }}
  labels:
{{ include "statping.labels" . | indent 4 }}
{{- end -}}
